### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by Dayks** [tlewis17/MSFSTouchPortalPlugin#1]
This looks like it could be absolutely amazing.  

Only snag for me is I haven’t got the foggiest how to install your work, **any chance of an “idiot’s guide” to getting this up and running?**

I’m using touch-portal as a selection of virtual buttons passing keystrokes, having simconnect pass information both ways is a much better way and would get round my button state issue (button only knows it was pressed in touch-portal but can’t recognize a changed state due to the game).

I’d love to offer help but I’m an ideas guy (and irl pilot) not a software guru.

Cheers,

Dayks

**Comment by tlewis17** [comment]
Go to the releases:
https://github.com/tlewis17/MSFSTouchPortalPlugin/releases

Get the latest version and there will be a TPP file you can download. From Touch Portal go to Import Plugin. Once you have done that restart Touch Portal. After that you will have a list of new actions you can choose from. Also "Dynamic Text" variables are now available. You can see them from the Dynamic Text Updater, or you can add an option for "On Plugin State Change" then select the corresponding state and "Changes to". 

For buttons you use this like:

"On Plugin State Changes AutoPilot Master changes to 1" Then add whatever logic you want like button visuals. Duplicate this and add one for "does not change to 1" and that is when a button turns off. 

This is very much a work in progress!
Sample TML files can be found by FordMustang:
https://github.com/FordMustang0288/MSFSTouchPortalPages

I'll have more documentation as I go along. Just keep in mind, this is very much a work in progress.

**Comment by Dayks** [comment]
This is brilliant - I’ve got a pretty much fully functioning Autopilot panel for light aircraft set up.  Most of what I wanted was already done with keybinds but this is so much neater and the buttons can be reactive.

For instance I now have ALT & VS buttons which go green text when they are the active mode and white when they are not.  I can VS climb and on reaching the target alt the ALT button goes green and the VS goes white.

I’m going to work on the similar logic with the horizontal modes when I next get a bit of time.

Your setup steps as shown above were spot on and made the rest pretty intuitive.

Thank you!

**Comment by tlewis17** [comment]
Great to hear! I highly recommend you join the Touch Portal Discord, and there is a MSFS channel where we discuss this plugin and MSFS usages a lot. Would be great to have some Pilot expertise in there. I'm pretty new to flight sims.
