### ISSUE TITLE
Implement Auto Pilot FLC mode

### ISSUE THREAD

**Issue by tlewis17** [tlewis17/MSFSTouchPortalPlugin#12]
* Autopilot FLC - Flight Level Change (set & state)

This doesn't seem like it is available through SimConnect at the moment.

**Comment by timroes** [comment]
It seems those are (nowadays) availble according to the documentation on https://docs.flightsimulator.com/html/Programming_Tools/SimConnect/SimConnect_SDK.htm

There should be a [`AUTOPILOT FLIGHT LEVEL CHANGE`](https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Aircraft_SimVars/Aircraft_AutopilotAssistant_Variables.htm) variable to toggle it, and corresponding [`AP_FLIGHT_LEVEL_CHANGE_ON/OFF`](https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Event_IDs/Aircraft_Autopilot_Flight_Assist_Events.htm) events.

Might those be available despite not being linked on the variables/events IDs mentioned in the README? Sorry, haven't done any SimConnect coding, so not sure I understand the bigger picture here.
