### ISSUE TITLE
Adding KEY_G1000_PFD_SOFTKEY1 to 12

### ISSUE THREAD

**Issue by jlr91** [tlewis17/MSFSTouchPortalPlugin#35]
I'd like to use buttons in order to Initiate the action for the icon displayed in the softkey position. 

 category : Instruments

Implementing these buttons
![fc142ac8cbcb84807e5e74146c94690caff56158](https://user-images.githubusercontent.com/83365849/116448888-e1df5e00-a859-11eb-8e5b-70bf8e1d8449.jpg)

Many thanks for this great plugin !

**Comment by tlewis17** [comment]
Thanks for the screenshot, that helps a lot.
