### ISSUE TITLE
Avionics state

### ISSUE THREAD

**Issue by cindercide** [tlewis17/MSFSTouchPortalPlugin#36]
**What data would you like to see in Touch Portal that comes from your simulator/aircraft?**
Avionics switch state for general aviation aircraft

**Provide the category of the action if you know it. Engines, Instruments, Environment, etc.**
Instruments - Electrical

**Additional context**

AVIONICS_MASTER_SWITCH
CIRCUIT_AVIONICS_ON   ??

**Comment by tlewis17** [comment]
Will release with 1.0 coming up soon.
