### ISSUE TITLE
Not working with SU7

### ISSUE THREAD

**Issue by junglejuz** [tlewis17/MSFSTouchPortalPlugin#39]
None of the action commands work for me. 

I've tried the FlyByWire + Cj4  template pages from https://flightsim.to/file/7406/touchportal-a320neo-flybywire, and also the FltSim-msfs2020-Control template from https://github.com/HiDTH/FltSim-msfs2020-Control/. I've also tried adding basic functions on a blank page.

These pre-built pages both say MSFS is connected and they pick up the flight data but none of the buttons/functions work for me. I haven't changed any of the default key bindings in MSFS so that shouldn't be affecting it.

Using:
v2.3.010 of Touch Portal on iPad,
v0.5.3 of the plugin
MSFS 2020 SU7

**Comment by junglejuz** [comment]
after lots of screwing around, i ran touch portal as admin and it seems to be working now

**Comment by tlewis17** [comment]
Yeah, Touch Portal launches the plugin in the same user context as Touch Portal. And it can only effectively communicate with MSFS in the same context. If your MSFS runs as admin, the other two have to as well.
