### ISSUE TITLE
SimConnect status alway disconnected.

### ISSUE THREAD

**Issue by billydragon** [tlewis17/MSFSTouchPortalPlugin#4]
I try your plugins with MSFS 2020 but alway Simconnect disconnected. Not working with simconnect function like Autopilot.
here is my log:

13:37:03.927 - [LOG] Startup Parameters: None found
13:37:04.923 - [LOG] *** TOUCH PORTAL START EVENT ***
13:37:04.926 - [LOG] (Date) 2020-SEPTEMBER-28
13:37:06.758 - [LOG] (Initializing TP) Checking config file...
13:37:06.760 - [LOG] (Initializing TP) Checking main page integrity file...
13:37:06.761 - [LOG] (Initializing TP) Checking firewall sanity...
13:37:06.773 - [LOG] Touch Portal is Running on Java version: 1.8.0_261
13:37:06.777 - [LOG] Java JRE / SDK location: C:\Program Files\Java\jre1.8.0_261
13:37:06.778 - [LOG] Firewall Entry: C:\Program Files\Java\jre1.8.0_261\bin\javaw.exe
13:37:07.184 - [LOG] Touch Portal is on a public network profile
13:37:07.860 - [LOG] (Initializing TP) Checking Java version...
13:37:07.861 - [LOG] (Initializing TP) Checking language settings...
13:37:07.865 - [LOG] (Initializing TP) Checking settings file...
13:37:07.866 - [LOG] (Settings) Create settings file if not already existing
13:37:07.867 - [LOG] (Settings) Settings file already exists
13:37:07.868 - [LOG] (Initializing TP) Checking Twitter configuration...
13:37:07.870 - [ERROR] (Twitter) Could not authenticate twitter. Token and/or secret is empty.
13:37:07.870 - [LOG] (Initializing TP) Checking Philips Hue configuration...
13:37:07.873 - [LOG] (Initializing TP) Starting State Services v1...
13:37:08.250 - [LOG] (Initializing TP) Starting State Services v2...
13:37:08.253 - [LOG] (Initializing TP) Initializing Auto Text Updater system...
13:37:08.259 - [LOG] (Initializing TP) Starting Communication services...
13:37:08.306 - [LOG] (Twitch) Cannot start Twitch integration as Twitch is not setup in Touch Portal.
13:37:08.307 - [LOG] (Initializing TP) Initializing Custom state system services...
13:37:08.315 - [LOG] (Initializing TP) Loading plug-ins...
13:37:08.317 - [LOG] (Plugin System) Searching and loading plugins...
13:37:08.322 - [LOG] (Plugin System) Base Folder: MSFS-TouchPortal-Plugin
13:37:08.339 - [LOG] (Plugin System) (127.0.0.1) Waiting for request on port 12136...
13:37:08.381 - [LOG] (Plugin System) Added Category: MSFS - AutoPilot
13:37:08.383 - [LOG] (Plugin System) Added Category: MSFS - Communication
13:37:08.386 - [LOG] (Plugin System) Added Category: MSFS - Electrical
13:37:08.390 - [LOG] (Plugin System) Added Category: MSFS - Engine
13:37:08.401 - [LOG] (Plugin System) Added Category: MSFS - Environment
13:37:08.404 - [LOG] (Plugin System) Added Category: MSFS - Failures
13:37:08.407 - [LOG] (Plugin System) Added Category: MSFS - Flight Instruments
13:37:08.413 - [LOG] (Plugin System) Added Category: MSFS - Flight Systems
13:37:08.416 - [LOG] (Plugin System) Added Category: MSFS - Fuel
13:37:08.417 - [LOG] (Plugin System) Added Category: MSFS - Menu
13:37:08.419 - [LOG] (Plugin System) Added Category: MSFS - Plugin
13:37:08.421 - [LOG] (Plugin System) Base Folder: tpwe
13:37:08.425 - [LOG] (Plugin System) No Events found for the plugin.
13:37:08.426 - [LOG] (Plugin System) Added Category: TP Windows Essentials
13:37:08.427 - [LOG] (Plugin System) Base Folder: vJoyTP
13:37:08.430 - [LOG] (Plugin System) No Events found for the plugin.
13:37:08.431 - [LOG] (Plugin System) Added Category: vJoyTP
13:37:08.454 - [LOG] (Starting GUI) Main screen start
13:37:08.751 - [LOG] (Starting GUI) Initializing OBS communication...
13:37:08.781 - [LOG] (Starting GUI) Initializing general app settings...
13:37:09.018 - [LOG] (Starting GUI) Initializing fonts...
13:37:09.095 - [LOG] (Starting GUI) Initializing controls...
13:37:09.105 - [LOG] (Starting GUI) Initializing main field...
13:37:09.118 - [LOG] (Starting GUI) Initializing page properties...
13:37:09.169 - [LOG] (Starting GUI) Initializing network controls...
13:37:09.174 - [LOG] (Starting GUI) Get local ips...
13:37:09.386 - [LOG] Found network interface for Server: eth0 - /192.168.0.5
13:37:09.456 - [LOG] Found network interface for Server: net6 - /10.8.0.6
13:37:09.461 - [LOG] (Starting GUI) Add USB connection item...
13:37:09.473 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:09.464 - [LOG] (Starting GUI) Loading last connection value...
13:37:09.608 - [LOG] (Starting GUI) Setup selection model...
13:37:09.609 - [LOG] (Starting GUI) Creating simple controls...
13:37:09.611 - [LOG] (Starting GUI) Update connection indicator...
13:37:09.612 - [LOG] (Starting GUI) Done...
13:37:09.616 - [LOG] (Starting GUI) Initializing global settings...
13:37:09.621 - [LOG] (Starting GUI) Initializing main scene...
13:37:09.645 - [LOG] (Starting GUI) Initializing pages...
13:37:09.649 - [LOG] (Starting GUI) Loading (main) page...
13:37:09.845 - [LOG] (Starting GUI) Initializing tutorials if needed...
13:37:11.080 - [LOG] (Plugin System) Executing plugin service: C:\Users\duongnt\AppData\Roaming\TouchPortal\plugins\\MSFS-TouchPortal-Plugin\dist\MSFSTouchPortalPlugin.exe
13:37:11.538 - [LOG] (Plugin System) Creating plugin instance connection on port 12136 on 127.0.0.1
13:37:11.542 - [LOG] (Plugin System) (127.0.0.1) Waiting for request on port 12136...
13:37:11.708 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Plugin.State.Connected from false to value true
13:37:11.995 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.MasterAlternator from  to value 1
13:37:11.997 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.MasterBattery from  to value 1
13:37:11.999 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightBeaconOn from  to value 1
13:37:12.001 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightBrakeOn from  to value 0
13:37:12.003 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightCabinOn from  to value 1
13:37:12.005 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightHeadOn from  to value 0
13:37:12.007 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightLandingOn from  to value 1
13:37:12.009 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightLogoOn from  to value 1
13:37:12.010 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightNavOn from  to value 1
13:37:12.012 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightPanelOn from  to value 1
13:37:12.014 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightRecognitionOn from  to value 1
13:37:12.016 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightStrobeOn from  to value 1
13:37:12.018 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightTaxiOn from  to value 0
13:37:12.020 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Electrical.State.LightWingOn from  to value 1
13:37:12.022 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Engine.State.MasterIgnitionSwitch from  to value 1
13:37:12.024 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightInstruments.State.GroundVelocity from  to value 0 KTS
13:37:12.026 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightInstruments.State.PlaneAltitude from  to value 13,4 FT
13:37:12.028 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightInstruments.State.PlaneAltitudeAGL from  to value 3,9 FT
13:37:12.030 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightInstruments.State.GroundAltitude from  to value 9,5 FT
13:37:12.032 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightInstruments.State.PlaneHeadingTrue from  to value 252 Deg.
13:37:12.034 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightInstruments.State.PlaneHeadingMagnetic from  to value 254 Deg.
13:37:12.037 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightInstruments.State.PlaneBankAngle from  to value 0 Deg.
13:37:12.038 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightInstruments.State.PlanePitchAngle from  to value 0 Deg.
13:37:12.040 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightSystems.State.GearTotalExtended from  to value 1
13:37:12.042 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightSystems.State.AileronTrim from  to value 0
13:37:12.044 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightSystems.State.ElevatorTrim from  to value 2,9382451415453468
13:37:12.046 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightSystems.State.RudderTrim from  to value 0
13:37:12.048 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.FlightSystems.State.RudderTrimPct from  to value 0
13:37:12.049 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotMaster from  to value 0
13:37:12.051 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotAvailable from  to value 1
13:37:12.053 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotPitchHold from  to value 0
13:37:12.055 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotAttitudeHold from  to value 0
13:37:12.057 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotAttitudeVar from  to value 0,46889606169851905
13:37:12.059 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotApproachHold from  to value 0
13:37:12.061 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotBanking from  to value 25,00000012650595
13:37:12.063 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotHeadingHold from  to value 0
13:37:12.064 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotHeadingVar from  to value 0
13:37:12.066 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotAltitudeHold from  to value 0
13:37:12.068 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotAltitudeVar from  to value 0
13:37:12.070 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotBackCourseHold from  to value 0
13:37:12.072 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotNav1Hold from  to value 0
13:37:12.074 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotNavSelected from  to value 1
13:37:12.076 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotVerticalSpeedHold from  to value 0
13:37:12.078 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotVerticalSpeedVar from  to value 0
13:37:12.080 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotAirSpeedHold from  to value 0
13:37:12.082 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotAirSpeedVar from  to value 0
13:37:12.084 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoThrottleArm from  to value 0
13:37:12.086 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoThrottleGA from  to value 0
13:37:12.087 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotMach from  to value 0
13:37:12.089 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotMachVar from  to value 0,020266180858016014
13:37:12.091 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotFlightDirector from  to value 0
13:37:12.092 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotFlightDirectorCurrentPitch from  to value 0,46889606169851905
13:37:12.094 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotWingLeveler from  to value 0
13:37:12.096 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.AutoPilot.State.AutoPilotYawDampener from  to value 0
13:37:12.122 - [ERROR] (OBS) Could not connect: Connection failed. - Touch Portal will try to reconnect every 4 seconds...
13:37:12.123 - [LOG] (OBS) Canceling OBS connection thread...
13:37:12.124 - [LOG] (OBS) Connection OBS failed (2): sleep interrupted
13:37:37.539 - [LOG] (192.168.0.5) Received request on port 12134...
13:37:37.545 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:40.927 - [LOG] (192.168.0.5) Received request on port 12134...
13:37:40.929 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:40.963 - [LOG] (192.168.0.5) Received request on port 12134...
13:37:40.965 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:40.971 - [LOG] (192.168.0.5) Received request on port 12134...
13:37:40.973 - [LOG] (Actions) Button State UP for index: (0, 0) on page (main)
13:37:40.974 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:40.977 - [LOG] (Actions) Doing action Go To page
13:37:50.972 - [LOG] (192.168.0.5) Received request on port 12134...
13:37:50.974 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:51.048 - [LOG] (192.168.0.5) Received request on port 12134...
13:37:51.050 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:51.051 - [LOG] (Actions) Button State UP for index: (2, 0) on page msfstpp_main
13:37:51.054 - [LOG] (192.168.0.5) Received request on port 12134...
13:37:51.056 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:51.057 - [LOG] (Actions) Doing action MSFS
13:37:51.179 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Plugin.State.Connected from true to value false
13:37:51.180 - [LOG] (Actions) Event Triggered: When MSFS - Plugin - The status of SimConnect is
13:37:51.181 - [LOG] (Actions) * Action triggered by event: Visuals - Change visuals for the Title
13:37:52.343 - [LOG] (192.168.0.5) Received request on port 12134...
13:37:52.346 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:52.479 - [LOG] (192.168.0.5) Received request on port 12134...
13:37:52.481 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:52.482 - [LOG] (Actions) Button State UP for index: (2, 0) on page msfstpp_main
13:37:52.507 - [LOG] (192.168.0.5) Received request on port 12134...
13:37:52.509 - [LOG] (192.168.0.5) Waiting for request on port 12134...
13:37:52.511 - [LOG] (Actions) Doing action MSFS

**Comment by FordMustang0288** [comment]
Tough to see the log on mobile but I have a suggestion for you to try. 
Once you have msfs open, navigate to %appdata%/TouchPortal/plugins and open the .exe there. You should see a cmd open and show that it is receiving OR you’ll get an error message. 

I wonder if this will work for you as another test case to debug with.

**Comment by tlewis17** [comment]
The latest version should work for this functionality. In fact, you can see in your log:
13:37:51.179 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Plugin.State.Connected from true to value false

What does your button look like in Touch Portal?

**Comment by billydragon** [comment]
I did't modify any thing. just install plugin and pages as instruction in readme. here is log file exe running after MSFS loaded in cockpit view.

c:\Users\billy\AppData\Roaming\TouchPortal\plugins\MSFS-TouchPortal-Plugin\dist>MSFSTouchPortalPlugin.exe
Connect SimConnect
Opened
SimConnect_OnRecvException: UNRECOGNIZED_ID
SimConnect_OnRecvException: UNRECOGNIZED_ID
SimConnect_OnRecvException: UNRECOGNIZED_ID
SimConnect_OnRecvException: UNRECOGNIZED_ID
SimConnect_OnRecvException: UNRECOGNIZED_ID
SimConnect_OnRecvException: UNRECOGNIZED_ID
29/09/2020 4:20:49 SA Recieved: -1 -
SimConnect_OnRecvException: NAME_UNRECOGNIZED
SimConnect_OnRecvException: NAME_UNRECOGNIZED
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
SimConnect_OnRecvException: UNRECOGNIZED_ID
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
SimConnect_OnRecvException: UNRECOGNIZED_ID
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
ReceivedObjectDataByType
...

**Comment by billydragon** [comment]
I try log again TouchPortal MSFS plugin stop then start again. Simconnect still Disconnected. Try button to connect no success. Here is log.

04:25:33.789 - [LOG] (Plugin System) Executing plugin service: C:\Users\billy\AppData\Roaming\TouchPortal\plugins\\MSFS-TouchPortal-Plugin\dist\MSFSTouchPortalPlugin.exe
04:25:34.035 - [LOG] (Plugin System) Creating plugin instance connection on port 12136 on 127.0.0.1
04:25:34.036 - [LOG] (Plugin System) (127.0.0.1) Waiting for request on port 12136...
04:25:34.155 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Plugin.State.Connected from false to value true
04:25:51.209 - [LOG] (192.168.1.10) Received request on port 12134...
04:25:51.210 - [LOG] (192.168.1.10) Waiting for request on port 12134...
04:25:51.309 - [LOG] (192.168.1.10) Received request on port 12134...
04:25:51.310 - [LOG] (192.168.1.10) Waiting for request on port 12134...
04:25:51.312 - [LOG] (Actions) Button State UP for index: (0, 0) on page (main)
04:25:51.315 - [LOG] (192.168.1.10) Received request on port 12134...
04:25:51.316 - [LOG] (192.168.1.10) Waiting for request on port 12134...
04:25:51.318 - [LOG] (Actions) Doing action Set Button State
04:25:51.320 - [LOG] (Actions) Doing action Visuals
04:25:51.321 - [LOG] (Actions) Event Triggered: On Button State Change
04:25:51.322 - [LOG] (Actions) - Action triggered by event: Wait for - 100 milliseconds
04:25:51.423 - [LOG] (Actions) - Action triggered by event: Set Button State -  OFF
04:25:51.424 - [LOG] (Actions) - Action triggered by event: Visuals - Change visuals for the Background colors
04:25:51.424 - [LOG] (Actions) - Action triggered by event: Go To page - msfstpp_main
04:25:53.302 - [LOG] (192.168.1.10) Received request on port 12134...
04:25:53.304 - [LOG] (192.168.1.10) Waiting for request on port 12134...
04:25:53.439 - [LOG] (192.168.1.10) Received request on port 12134...
04:25:53.440 - [LOG] (192.168.1.10) Waiting for request on port 12134...
04:25:53.441 - [LOG] (Actions) Button State UP for index: (2, 0) on page msfstpp_main
04:25:53.447 - [LOG] (192.168.1.10) Received request on port 12134...
04:25:53.449 - [LOG] (192.168.1.10) Waiting for request on port 12134...
04:25:53.450 - [LOG] (Actions) Doing action MSFS
04:25:53.578 - [LOG] (State System) Changed state MSFSTouchPortalPlugin.Plugin.State.Connected from true to value false
04:25:53.579 - [LOG] (Actions) Event Triggered: When MSFS - Plugin - The status of SimConnect is
04:25:53.580 - [LOG] (Actions) * Action triggered by event: Visuals - Change visuals for the Title

**Comment by billydragon** [comment]
I go to touch portal setting and manual stop/start MSFS Plugin then simconnect is working but status of button still Disconnected. If I press button then simconnect is diskconnected, togle function not working until go back to Touch portal setting and restart plugin again. button Simconnect is not update status simconnect as needed.

**Comment by tlewis17** [comment]
I don't believe Ford has the connection status updated on his page yet since I just released the version yesterday with it fixed. You may have to modify the button state. Here is a sample of what I use for it:

![image](https://user-images.githubusercontent.com/6618767/94513736-bf5e6700-01dc-11eb-9c53-9db57e0db769.png)

**Comment by billydragon** [comment]
Try change by your instructions and it work now. Thanks

**Comment by FordMustang0288** [comment]
I wasn’t sure if I should assume that my pages were being used. But yes, that button and state is not functional. I’m pretty sure my latest commit actually removed it because it seemed like you were doing things well in the background
