### ISSUE TITLE
Comms selector is misnamed as "Fuel Selector"

### ISSUE THREAD

**Issue by FordMustang0288** [tlewis17/MSFSTouchPortalPlugin#7]
Under communication actions, you can select "Fuel Selector". However, it is very clear that this was intended to be a COMMS selector as seen in the screenshots below.

![image](https://user-images.githubusercontent.com/31976175/95271156-2f877100-080b-11eb-8b5e-20bd59672399.png)

![image](https://user-images.githubusercontent.com/31976175/95271143-272f3600-080b-11eb-825b-a9e194690b8f.png)

**Comment by billydragon** [comment]
are it working? in my setting COMM not working
